server:
  port: 8081
  
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms4?useSSL=false&allowPublicKeyRetrieval=true
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
     
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    
  application:
    name: ms4-service-1
    
